# Generated by Django 5.2.7 on 2025-11-20 00:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('electionapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('my_number', models.CharField(max_length=12, unique=True)),
                ('gender', models.CharField(max_length=1)),
                ('birth_date', models.DateField()),
                ('address', models.CharField(max_length=50)),
                ('nationality', models.CharField(max_length=20)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electionapp.area')),
            ],
        ),
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_code', models.CharField(unique=True)),
                ('password', models.CharField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voter.personalinfo')),
            ],
        ),
        migrations.CreateModel(
            name='VoteStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=1)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='electionapp.election')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='voter.personalinfo')),
            ],
        ),
    ]
