# Generated by Django 5.2.7 on 2026-01-08 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electionapp', '0003_alter_candidate_face_photo'),
        ('voter', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='votestatus',
            constraint=models.UniqueConstraint(fields=('person', 'election'), name='one_vote_status_per_person_per_election'),
        ),
    ]
