# Generated by Django 5.2.7 on 2026-01-09 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0002_votestatus_one_vote_status_per_person_per_election'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='vote_code',
            field=models.CharField(blank=True, null=True, unique=True),
        ),
    ]
