# Generated by Django 5.2.7 on 2026-01-29 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0003_alter_voter_vote_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='current_session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
