# Generated by Django 5.2.7 on 2025-11-20 00:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='electionapp.area')),
            ],
        ),
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=20)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('administrator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administrator.administrator')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electionapp.area')),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('face_photo', models.ImageField(upload_to='candidate_photos/')),
                ('birth_date', models.DateField()),
                ('elected_count', models.IntegerField()),
                ('policy', models.TextField()),
                ('career', models.TextField()),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='electionapp.election')),
                ('party', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='electionapp.party')),
            ],
        ),
        migrations.CreateModel(
            name='VoteResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.IntegerField()),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='electionapp.candidate')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='electionapp.election')),
            ],
        ),
    ]
