# Generated by Django 5.2.7 on 2025-11-25 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electionapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='status',
            field=models.CharField(default='未実施', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='election',
            name='area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='electionapp.area'),
        ),
    ]
