# Generated by Django 5.2.7 on 2026-01-08 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electionapp', '0002_election_status_alter_election_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='face_photo',
            field=models.ImageField(blank=True, null=True, upload_to='candidate_photos/'),
        ),
    ]
