# Generated by Django 5.2.7 on 2026-01-13 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electionapp', '0003_alter_candidate_face_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartyVoteResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.IntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name='VoteResult',
            new_name='CandidateVoteResult',
        ),
        migrations.AddConstraint(
            model_name='candidatevoteresult',
            constraint=models.UniqueConstraint(fields=('election', 'candidate'), name='unique_candidate_vote'),
        ),
        migrations.AddField(
            model_name='partyvoteresult',
            name='election',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='electionapp.election'),
        ),
        migrations.AddField(
            model_name='partyvoteresult',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='electionapp.party'),
        ),
        migrations.AddConstraint(
            model_name='partyvoteresult',
            constraint=models.UniqueConstraint(fields=('election', 'party'), name='unique_party_vote'),
        ),
    ]
