# Generated by Django 5.2.7 on 2026-01-15 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electionapp', '0004_partyvoteresult_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='career',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='elected_count',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='face_photo',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='policy',
        ),
    ]
