# Generated by Django 5.2.7 on 2025-11-20 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_id', models.CharField()),
                ('password', models.CharField()),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
