# Generated by Django 5.2.7 on 2025-11-20 00:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrator', '0001_initial'),
        ('electionapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrator',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electionapp.area'),
        ),
    ]
